//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STech_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public string OrderID { get; set; }
        public string CustomerID { get; set; }
        public System.DateTime OrderDate { get; set; }
        public decimal TotalPrice { get; set; }
        public string Status { get; set; }
        public string Note { get; set; }
        public Nullable<decimal> DeliveryFee { get; set; }
        public Nullable<decimal> DepositedMoney { get; set; }
        public decimal TotalPaymentAmout { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
