//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STech_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsBackup
    {
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string ImgSrc { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Warranty { get; set; }
        public string BrandID { get; set; }
        public string CateID { get; set; }
    }
}
